### ISSUE TITLE
No CORS headers returned (again) if exception is raised with API Gateway Proxy + Lambda, GraalVM native image

### ISSUE THREAD

**Issue by uboznikov** [micronaut-projects/micronaut-aws#136] opened 2019-11-21 09:06 UTC
Micronaut version: 1.2.6

Setup:
I have an API Gateway Proxy + Lambda app created with `--features aws-api-gateway-graal`, but I'm temporarily using the Java8 runtime due to GraalVM's issue with the MySQL driver.

The issue I'm having is that there are no CORS headers returned when exceptions are raised, for example, HTTP input params validation errors.

Basically the same as with this:
https://github.com/micronaut-projects/micronaut-core/issues/1471

Also, I cannot use a custom exception handler due to this issue:
https://github.com/micronaut-projects/micronaut-aws/issues/125

In this case there were also no CORS headers returned.

**Comment by alvarosanchez** [comment] 2020-01-22 10:00
@uboznikov could you please upload a sample application that reproduces the issue?

**Comment by alvarosanchez** [comment] 2020-01-23 11:54
@uboznikov since #125 is now fixed, you can use a custom exception handler as a workaround for this issue.

**Closed** 2021-03-10 14:54 UTC
Labels: priority: high, status: pr submitted, type: bug
