### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Too many elements in the Publisher when returning Flux<X>

### ISSUE THREAD

**Issue by codependent** [micronaut-projects/micronaut-aws#51] opened 2019-06-28 08:11 UTC
Micronaut version 1.1.3

Given this simple code of a Lambda with proxy integration:

```kotlin
@Controller("/users")
class UserController(private val userService: UserService) {

    @Get
    fun getAll(): Flux<User> {
        return userService.getAll()
    }

}

@Singleton
class UserServiceImpl : UserService {

    private val users = mutableListOf(
            User("1234D", "Joe"),
            User("2345C", "Lewis"))

    override fun getAll(): Flux<User> {
        return users.toFlux()
    }
}

```

When calling `GET /users` from the API Gateway I get and exception with the message `Too many elements in the Publisher`, even though the Lambda only returns a Flux with two elements.

This is the full stacktrace:

```
%d [%thread] %-5level %logger - %msg%n java.lang.IndexOutOfBoundsException: Too many elements in the Publisher
at io.reactivex.internal.operators.single.SingleFromPublisher$ToSingleObserver.onNext(SingleFromPublisher.java:73) ~[task/:?]
at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[task/:?]
at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:311) ~[task/:?]
at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:198) ~[task/:?]
at reactor.core.publisher.StrictSubscriber.onSubscribe(StrictSubscriber.java:77) ~[task/:?]
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139) ~[task/:?]
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63) ~[task/:?]
at reactor.core.publisher.Flux.subscribe(Flux.java:7743) ~[task/:?]
at io.reactivex.internal.operators.single.SingleFromPublisher.subscribeActual(SingleFromPublisher.java:35) ~[task/:?]
at io.reactivex.Single.subscribe(Single.java:3575) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedSingle.subscribeActual(RxInstrumentedSingle.java:64) ~[task/:?]
at io.reactivex.Single.subscribe(Single.java:3575) ~[task/:?]
at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34) ~[task/:?]
at io.reactivex.Single.subscribe(Single.java:3575) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedSingle.subscribeActual(RxInstrumentedSingle.java:64) ~[task/:?]
at io.reactivex.Single.subscribe(Single.java:3575) ~[task/:?]
at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14755) ~[task/:?]
at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52) ~[task/:?]
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52) ~[task/:?]
at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52) ~[task/:?]
at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.internal.operators.flowable.FlowableOnErrorNext.subscribeActual(FlowableOnErrorNext.java:40) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.blockingFirst(Flowable.java:5607) ~[task/:?]
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$5(MicronautLambdaContainerHandler.java:274) ~[task/:?]
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52) ~[task/:?]
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:206) ~[task/:?]
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:73) ~[task/:?]
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:207) [task/:?]
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxyStream(AbstractLambdaContainerHandler.java:239) [task/:?]
at com.codependent.awsintercomm.user.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:24) [task/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64) [LambdaSandboxJava-1.0.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114) [LambdaJavaRTEntry-1.0.jar:?]
%d [%thread] %-5level %logger - %msg%n java.lang.IndexOutOfBoundsException: Too many elements in the Publisher
at io.reactivex.internal.operators.single.SingleFromPublisher$ToSingleObserver.onNext(SingleFromPublisher.java:73) ~[task/:?]
at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[task/:?]
at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:311) ~[task/:?]
at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:198) ~[task/:?]
at reactor.core.publisher.StrictSubscriber.onSubscribe(StrictSubscriber.java:77) ~[task/:?]
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139) ~[task/:?]
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63) ~[task/:?]
at reactor.core.publisher.Flux.subscribe(Flux.java:7743) ~[task/:?]
at io.reactivex.internal.operators.single.SingleFromPublisher.subscribeActual(SingleFromPublisher.java:35) ~[task/:?]
at io.reactivex.Single.subscribe(Single.java:3575) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedSingle.subscribeActual(RxInstrumentedSingle.java:64) ~[task/:?]
at io.reactivex.Single.subscribe(Single.java:3575) ~[task/:?]
at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34) ~[task/:?]
at io.reactivex.Single.subscribe(Single.java:3575) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedSingle.subscribeActual(RxInstrumentedSingle.java:64) ~[task/:?]
at io.reactivex.Single.subscribe(Single.java:3575) ~[task/:?]
at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14755) ~[task/:?]
at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52) ~[task/:?]
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52) ~[task/:?]
at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52) ~[task/:?]
at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.internal.operators.flowable.FlowableOnErrorNext.subscribeActual(FlowableOnErrorNext.java:40) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14752) ~[task/:?]
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68) ~[task/:?]
at io.reactivex.Flowable.subscribe(Flowable.java:14805) ~[task/:?]
at io.reactivex.Flowable.blockingFirst(Flowable.java:5607) ~[task/:?]
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$5(MicronautLambdaContainerHandler.java:274) ~[task/:?]
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52) ~[task/:?]
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:206) ~[task/:?]
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:73) ~[task/:?]
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:207) [task/:?]
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxyStream(AbstractLambdaContainerHandler.java:239) [task/:?]
at com.codependent.awsintercomm.user.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:24) [task/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64) [LambdaSandboxJava-1.0.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114) [LambdaJavaRTEntry-1.0.jar:?]
java.lang.IndexOutOfBoundsException: Too many elements in the Publisher
at io.reactivex.internal.operators.single.SingleFromPublisher$ToSingleObserver.onNext(SingleFromPublisher.java:73)
at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:311)
at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:198)
at reactor.core.publisher.StrictSubscriber.onSubscribe(StrictSubscriber.java:77)
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
at reactor.core.publisher.Flux.subscribe(Flux.java:7743)
at io.reactivex.internal.operators.single.SingleFromPublisher.subscribeActual(SingleFromPublisher.java:35)
at io.reactivex.Single.subscribe(Single.java:3575)
at io.micronaut.reactive.rxjava2.RxInstrumentedSingle.subscribeActual(RxInstrumentedSingle.java:64)
at io.reactivex.Single.subscribe(Single.java:3575)
at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
at io.reactivex.Single.subscribe(Single.java:3575)
at io.micronaut.reactive.rxjava2.RxInstrumentedSingle.subscribeActual(RxInstrumentedSingle.java:64)
at io.reactivex.Single.subscribe(Single.java:3575)
at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.subscribe(Flowable.java:14752)
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.subscribe(Flowable.java:14752)
at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.subscribe(Flowable.java:14752)
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.subscribe(Flowable.java:14755)
at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.subscribe(Flowable.java:14752)
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.internal.operators.flowable.FlowableOnErrorNext.subscribeActual(FlowableOnErrorNext.java:40)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.subscribe(Flowable.java:14752)
at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.blockingFirst(Flowable.java:5607)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$5(MicronautLambdaContainerHandler.java:274)
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:206)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:73)
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:207)
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxyStream(AbstractLambdaContainerHandler.java:239)
at com.codependent.awsintercomm.user.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
END RequestId: 846a2af9-559b-447f-9e47-43e66cda14b9
```

The behaviour is as expected when starting the project as a normal Micronaut application and requesting that endpoint: `[{"id":"1234D","name":"Joe"},{"id":"2345C","name":"Lewis"}]`

**Comment by graemerocher** [comment] 2019-06-28 08:50
ok, will have a look, somewhere it is doing toSingle() I imagine. btw I personally would not bother with reactive with serverless since lambdas are single threaded and the overhead is unnecessary

**Comment by faxdam1** [comment] 2019-11-14 14:18
I would like to have a fix for this bug, because I want to use back pressure feature. Thanks for your help.

- Controller

` @Get(value="listar", produces = MediaType.APPLICATION_JSON)
    public Flux<ClienteDto> listarClientes() {
        return clienteService.consultarClientes()
                .map(it-> mapper.map(it,ClienteDto.class));
    }`

- Domain

`public Flux<Cliente> consultarClientes() {
        return clienteRepository.consultarClientes();
    }
`

- Repository

`public Flux<Cliente> consultarClientes() {
         return  Flux.from(clienteDao.find())
                 .map(clienteModel -> mapper.map(clienteModel,Cliente.class))
                 .onErrorResume(error -> {
                    LOG.errorWithHttpAndStackTrace(new Exception(error));
                   return Mono.error(new Exception(error));
          });
    }`

`java.lang.IndexOutOfBoundsException: Too many elements in the Publisher\n\tat io.reactivex.internal.operators.single.SingleFromPublisher$ToSingleObserver.onNext(SingleFromPublisher.java:73)\n\tat reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)\n\tat reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)\n\tat reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)\n\tat com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onNext(ObservableToPublisher.java:68)\n\tat com.mongodb.async.client.AbstractSubscription.onNext(AbstractSubscription.java:135)\n\tat com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:203)\n\tat com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:159)\n\tat com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:101)\n\tat com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:85)\n\tat com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:136)\n\tat com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:100)\n\tat com.mongodb.async.client.MongoIterableSubscription.requestMoreData(MongoIterableSubscription.java:85)\n\tat com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:53)\n\tat com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:46)\n\tat com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)\n\tat com.mongodb.async.client.OperationExecutorImpl$1$1.onResult(OperationExecutorImpl.java:82)\n\tat com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)\n\tat com.mongodb.operation.FindOperation$3.onResult(FindOperation.java:807)\n\tat com.mongodb.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:364)\n\tat com.mongodb.operation.CommandOperationHelper$2.onResult(CommandOperationHelper.java:406)\n\tat com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)\n\tat com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:227)\n\tat com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)\n\tat com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:85)\n\tat com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:461)\n\tat com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:111)\n\tat com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)\n\tat com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:395)\n\tat com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:372)\n\tat com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:667)\n\tat com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:634)\n\tat com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510)\n\tat com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:507)\n\tat com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)\n\tat com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)\n\tat com.mongodb.internal.connection.tlschannel.async.AsynchronousTlsChannel$3$1.run(AsynchronousTlsChannel.java:151)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n`

**Comment by graemerocher** [comment] 2019-11-14 14:22
PRs welcome

**Comment by alvarosanchez** [comment] 2020-01-22 11:48
I have been able to reproduce the issue and am working on a fix

**Closed** 2020-01-22 12:31 UTC
Labels: status: pr submitted, type: bug
