### ISSUE TITLE
AWS Custom domain support custom runtime

### ISSUE THREAD

**Issue by cr4zyf1st** [micronaut-projects/micronaut-aws#69] opened 2019-09-17 12:04 UTC
Created an application using the aws-api-gateway-graal feature following the link 
https://micronaut-projects.github.io/micronaut-aws/latest/guide/#customRuntimes
I used the following fix to build 
https://github.com/micronaut-projects/micronaut-aws/issues/49

Micronaut version 1.2.1

After this i deploy to an aws lambda with an api gateway, call the ping endpoint and response is 200. Calling the same endpoint after adding a custom domain in AWS that uses the api gateway causes a 502 status along with the following error in the lambda logs which gets repeated seemingly until the lambda times out. 

> 11:40:34 WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set a
11:40:34 START RequestId: 54b57a52-049a-4303-aeb3-60763a20944b Version: $LATEST
11:40:34 END RequestId: 54b57a52-049a-4303-aeb3-60763a20944b
11:40:34 REPORT RequestId: 54b57a52-049a-4303-aeb3-60763a20944b Duration: 18.89 ms Billed Duration: 300 ms Memory Size: 3008 MB Max Memory Used: 77 MB Init Duration: 264.85 ms XRAY TraceId: 1-5d80c631-77a3481d1600ee0d1c4ebba9 SegmentId: 14e6aa5d6d1cebaf Sampled: true
11:40:38 START RequestId: 667ef73d-b2a7-4bc4-8423-9517dbbe294c Version: $LATEST
11:40:38 Invocation with requestId [667ef73d-b2a7-4bc4-8423-9517dbbe294c] failed: com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.getContainerConfig()java.lang.NoSuchMethodError: com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.getContainerConfig()
11:40:38 at com.amazonaws.serverless.proxy.internal.SecurityUtils.isValidHost(SecurityUtils.java:63)
11:40:38 at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getUri(MicronautAwsProxyRequest.java:167)
11:40:38 at io.micronaut.http.HttpRequest.getPath(HttpRequest.java:85)
11:40:38 at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:79)
11:40:38 at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:48)
11:40:38 at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:204)
11:40:38 at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:129)
11:40:38 at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:75)

**Comment by graemerocher** [comment] 2019-09-30 09:20
The Graal support was fixed in https://github.com/micronaut-projects/micronaut-aws/commit/0e9439dfca5e018130d716e43d20cbc640322889 

I cannot reproduce this exception with master

**Comment by graemerocher** [comment] 2019-09-30 10:38
Now I can reproduce this suddenly

**Closed** 2019-09-30 10:54 UTC
Labels: bug
