### ISSUE TITLE
The QueryValue annotation no longer works for micronaut version 2.2.0 apps that use the lambda runtime

### ISSUE THREAD

**Issue by deandelponte** [micronaut-projects/micronaut-aws#754] opened 2020-11-24 19:07 UTC
### Steps to reproduce

1. Check out the code at https://github.com/ddelponte/lambda-runtime-bug
1. Run the app using Java 11  Amazon Corretto and the command `./gradlew run`
1. Once the app is running, in your browser go to http://localhost:8080/search?searchText=derp

### Expected results
I would expect to see the parameter value pulled out of the URL and displayed in the page like `Your searchText = derp`

### Actual results
The param value is not pulled out, instead the param key is.  For example `Your searchText = searchText`

### Interesting observations

1. This works as expected if the runtime is switched from `lambda` to `netty`
1. A test has been added to `BookControllerSpec` for this bug, but the test passes. The failure only occurs when accessing the running app through a browser.  I'm using Chrome version 86.0.4240.198

### Environment Information

- **Operating System**: MacOs 10.15.7
- **Micronaut Version:** 2.2.0
- **JDK Version:**  Corretto-11.0.8.10.1 

### Example Application

- https://github.com/ddelponte/lambda-runtime-bug

**Comment by ttzn** [comment] 2020-11-26 00:05
I got the same thing when using `./gradlew run`. However I am unable to reproduce using
 SAM CLI, are you sure it also happens in AWS ?

**Comment by deandelponte** [comment] 2020-12-01 16:07
> I got the same thing when using `./gradlew run`. However I am unable to reproduce using SAM CLI, are you sure it also happens in AWS ?

I did not deploy to AWS because it wasn't working locally with `gradle run` so it wouldn't be a good experience for our developers.

How do I run it locally with SAM CLI?  Thanks!

**Comment by ttzn** [comment] 2020-12-01 17:53
Have a look at [the official installation guide](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html). Unfortunately the process is quite involved. When you're set, unzip the attached archive somewhere and you should be able to simulate lambda execution with `sam local invoke "HelloWorldFunction" -e api-event.json`.

If you haven't observed this bug in AWS then I guess it's just a problem with `./gradlew run`, which should be fixed with my merge request. I'd suggest you drop a little +1 so it comes to the maintainers attention.

[lambda-runtime-bug-sam.zip](https://github.com/micronaut-projects/micronaut-aws/files/5624422/lambda-runtime-bug-sam.zip)

**Comment by deandelponte** [comment] 2020-12-01 17:57
Thanks!  You rock!  FYI - it looks like some checks failed on the PR

**Closed** 2020-12-05 05:19 UTC
Labels: type: bug
